name: price_compare
description: A Flutter app for comparing prices across stores.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  provider: ^6.0.0
  image_picker: ^1.0.7
  file_picker: ^9.2.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.0

flutter:
  uses-material-design: true

assets:
  - image/